#!/usr/bin/env node
/**
 * wire schema 双发射器（审查步骤 7，Node 零新依赖）。
 *
 * 源：`bridge/schema/wire.schema.json`（wire 面单一事实来源）。
 * 发射：
 *   1. `bridge/js/src/generated/wire-types.ts`        —— TS 类型面（WIRE 常量 +
 *      WireMethodOf<N> 方法联合、aliases、dynamicSinks）；
 *   2. `domain/src/main/kotlin/com/autoscript/domain/bridge/generated/WireMethods.kt`
 *      —— Kotlin 方法表（BY_NS / ALIASES），handler 的 `methods()` 逐个指到 BY_NS。
 *
 * 生成物**入库**（评审面可见、离线可读）；漂移即红：
 *   - `node generate.mjs --check`（wire-schema.test.cjs 每次 npm test 都跑）
 *   - CI `npm run gen:wire && git diff --exit-code`
 *
 * 路径以本文件位置为锚（不依赖 CWD），可从任意目录调用。
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(HERE, '..', '..')
const SCHEMA_PATH = path.join(HERE, 'wire.schema.json')
const TS_OUT = path.join(ROOT, 'bridge/js/src/generated/wire-types.ts')
const KT_OUT = path.join(ROOT, 'domain/src/main/kotlin/com/autoscript/domain/bridge/generated/WireMethods.kt')

const schema = JSON.parse(fs.readFileSync(SCHEMA_PATH, 'utf8'))

const REQUIRED = ['$note', 'namespaces', 'aliases', 'dynamicSinks']
for (const k of REQUIRED) {
  if (!(k in schema)) throw new Error(`wire.schema.json 缺字段 ${k}`)
}

function emitTs() {
  const nsKeys = Object.keys(schema.namespaces).sort()
  const aliasKeys = Object.keys(schema.aliases).sort()
  const lines = []
  lines.push('/* eslint-disable */')
  lines.push('// AUTO-GENERATED by bridge/schema/generate.mjs — DO NOT EDIT.')
  lines.push('// 源：bridge/schema/wire.schema.json（wire 面单一事实来源）。')
  lines.push('// 再生成：npm --prefix bridge/js run gen:wire（漂移由 wire-schema.test.cjs --check 看着）。')
  lines.push('')
  lines.push('/** wire 面方法表（schema 同源）。facade 列 = 该命名空间的 TS 门面文件。 */')
  lines.push('export const WIRE = {')
  for (const ns of nsKeys) {
    const v = schema.namespaces[ns]
    const methods = v.methods.map((m) => `'${m}'`).join(', ')
    lines.push(`  ${JSON.stringify(ns)}: { facade: '${v.facade}', methods: [${methods}] },`)
  }
  lines.push('} as const')
  lines.push('')
  lines.push('/** 命名空间字面量联合。 */')
  lines.push('export type WireNamespace = keyof typeof WIRE')
  lines.push('')
  lines.push("/** `invoke(ns, m)` 的 m 在该 ns 下的合法字面量联合（收窄签名用的类型面）。 */")
  lines.push('export type WireMethodOf<N extends WireNamespace> = (typeof WIRE)[N][\'methods\'][number]')
  lines.push('')
  lines.push('/** 宿主收、facade 不发的 wire 名 → 所在 ns + 理由（schema aliases 同源）。 */')
  lines.push(
    'export const WIRE_ALIASES: Readonly<Record<string, { readonly ns: string; readonly why: string }>> = {',
  )
  for (const k of aliasKeys) {
    const a = schema.aliases[k]
    lines.push(`  ${JSON.stringify(k)}: { ns: ${JSON.stringify(a.ns)}, why: ${JSON.stringify(a.why)} },`)
  }
  lines.push('}')
  lines.push('')
  lines.push('/** invoke 之外的 JS 方法字面量入口（解析器按 form 映射正则；schema dynamicSinks 同源）。 */')
  lines.push(
    "export const WIRE_DYNAMIC_SINKS: Readonly<readonly { readonly file: string; readonly ns: string; readonly form: string; readonly why: string }[]> = [",
  )
  for (const s of schema.dynamicSinks) {
    lines.push(
      `  { file: ${JSON.stringify(s.file)}, ns: ${JSON.stringify(s.ns)}, form: ${JSON.stringify(s.form)}, why: ${JSON.stringify(s.why)} },`,
    )
  }
  lines.push(']')
  lines.push('')
  return lines.join('\n')
}

function emitKt() {
  const nsKeys = Object.keys(schema.namespaces).sort()
  const aliasKeys = Object.keys(schema.aliases).sort()
  const lines = []
  lines.push('// AUTO-GENERATED by bridge/schema/generate.mjs — DO NOT EDIT.')
  lines.push('// 源：bridge/schema/wire.schema.json（wire 面单一事实来源，审查步骤 7）。')
  lines.push('// 再生成：npm --prefix bridge/js run gen:wire（漂移由 wire-schema.test.cjs --check 看着）。')
  lines.push('package com.autoscript.domain.bridge.generated')
  lines.push('')
  lines.push('/**')
  lines.push(' * wire 面方法表（schema 生成物，入库）。')
  lines.push(' *')
  lines.push(' * **为什么不手写**：同一张表散在 19 个 handler 的 `when` 里时，改名要碰两侧且')
  lines.push(' * 没人对账（wire 层漂移历史上咬过两次：`audit` 键名、`a11y.waitFor`）。现在')
  lines.push(' * schema 是单一事实来源，本文件与 `bridge/js/src/generated/wire-types.ts` 同批')
  lines.push(' * 发射，handler 的 [com.autoscript.domain.bridge.NamespaceHandler.methods] 逐个')
  lines.push(' * 指到 [WireMethods.BY_NS] —— 对账门 `wire-schema.test.cjs` 钉四向一致。')
  lines.push(' */')
  lines.push('object WireMethods {')
  lines.push('    /** ns → 方法表（与 schema 逐字同源；键序/表序由生成器固定，diff 可读）。 */')
  lines.push('    val BY_NS: Map<String, Set<String>> = mapOf(')
  for (const ns of nsKeys) {
    const ms = schema.namespaces[ns].methods
    lines.push(`        ${JSON.stringify(ns)} to setOf(`)
    for (let i = 0; i < ms.length; i += 6) {
      const chunk = ms.slice(i, i + 6).map((m) => JSON.stringify(m)).join(', ')
      lines.push(`            ${chunk},`)
    }
    lines.push('        ),')
  }
  lines.push('    )')
  lines.push('')
  lines.push('    /** 宿主收、facade 不发的 wire 名（schema aliases 同源）——理由是契约的一部分。 */')
  lines.push('    data class Alias(val ns: String, val why: String)')
  lines.push('')
  lines.push('    val ALIASES: Map<String, Alias> = mapOf(')
  for (const k of aliasKeys) {
    const a = schema.aliases[k]
    lines.push(`        ${JSON.stringify(k)} to Alias(${JSON.stringify(a.ns)},`)
    lines.push(`            ${JSON.stringify(a.why)},`)
    lines.push('        ),')
  }
  lines.push('    )')
  lines.push('}')
  lines.push('')
  return lines.join('\n')
}

function writeOrCheck(outPath, content) {
  if (process.argv.includes('--check')) {
    const cur = fs.existsSync(outPath) ? fs.readFileSync(outPath, 'utf8') : null
    if (cur !== content) {
      console.error(`生成物漂移：${path.relative(ROOT, outPath)}（跑 npm run gen:wire 后提交）`)
      process.exitCode = 1
    }
    return
  }
  fs.mkdirSync(path.dirname(outPath), { recursive: true })
  fs.writeFileSync(outPath, content)
}

writeOrCheck(TS_OUT, emitTs())
writeOrCheck(KT_OUT, emitKt())
if (process.exitCode !== 1 && !process.argv.includes('--check')) {
  console.log(`生成完成：\n  ${path.relative(ROOT, TS_OUT)}\n  ${path.relative(ROOT, KT_OUT)}`)
}
